version: "3"
services:
  mysql:
    image: kuangyu0801/powerstation-mysql-database
  api:
    image: kuangyu0801/powerstation-spring-backend:v2
    depends_on:
      - mysql
  client:
    image: kuangyu0801/powerstation-angular-frontend:v2
  nginx:
    image: kuangyu0801/powerstation-nginx:v2
    # nginx is lightweight and critial, always restart
    restart: always
    ports:
        # mapping localhost 4200 to default nginx port 80
        - '4200:80'
    depends_on: 
        - api
        - client